### ISSUE TITLE
Database Connection via ActiveDirectoryServicePrincipal for AZURE

### ISSUE THREAD

**Issue by Bauer-David** [innoventsolutions/birt-spring-boot#14]
I have tried to use BIRT as a service in the AZURE Cloud. So far the service is running and can communicate with my application. But as soon as I want to print a report and BIRT wants to connect to the database, I get the following error message:

```
org.eclipse.birt.report.engine.api.EngineException: An exception occurred during processing. 
Please see the following message for details:Cannot open the connection for the driver: org.eclipse.birt.report.data.oda.jdbc.   
org.eclipse.birt.report.data.oda.jdbc.JDBCException: There is an error in get connection, The authentication value "ActiveDirectoryServicePrincipal" is not valid..	
at org.eclipse.birt.report.engine.executor.ExecutionContext.addException(ExecutionContext.java:1252) ~[org.eclipse.birt.runtime_4.8.0-20180626-4.8.0.jar!/:na]	
at org.eclipse.birt.report.engine.executor.ExecutionContext.addException(ExecutionContext.java:1231) ~[org.eclipse.birt.runtime_4.8.0-20180626-4.8.0.jar!/:na]	
at org.eclipse.birt.report.engine.executor.QueryItemExecutor.executeQuery(QueryItemExecutor.java:96) ~[org.eclipse.birt.runtime_4.8.0-20180626-4.8.0.jar!/:na]	
at org.eclipse.birt.report.engine.executor.DataItemExecutor.execute(DataItemExecutor.java:75) ~[org.eclipse.birt.runtime_4.8.0-20180626-4.8.0.jar!/:na]
at org.eclipse.birt.report.engine.executor.ReportExecutorUtil.executeAll(ReportExecutorUtil.java:87) ~[org.eclipse.birt.runtime_4.8.0-20180626-4.8.0.jar!/:na]	
at org.eclipse.birt.report.engine.executor.ReportExecutorUtil.executeAll(ReportExecutorUtil.java:92) ~[org.eclipse.birt.runtime_4.8.0-20180626-4.8.0.jar!/:na]	
at org.eclipse.birt.report.engine.executor.ReportExecutorUtil.executeAll(ReportExecutorUtil.java:92) ~[org.eclipse.birt.runtime_4.8.0-20180626-4.8.0.jar!/:na]	
at org.eclipse.birt.report.engine.executor.ReportExecutorUtil.executeAll(ReportExecutorUtil.java:92) ~[org.eclipse.birt.runtime_4.8.0-20180626-4.8.0.jar!/:na]	
at org.eclipse.birt.report.engine.executor.ReportExecutorUtil.executeAll(ReportExecutorUtil.java:92) ~[org.eclipse.birt.runtime_4.8.0-20180626-4.8.0.jar!/:na]	
at org.eclipse.birt.report.engine.executor.ReportExecutor.createPageExecutor(ReportExecutor.java:229) ~[org.eclipse.birt.runtime_4.8.0-20180626-4.8.0.jar!/:na]	
at org.eclipse.birt.report.engine.internal.executor.wrap.WrappedReportExecutor.createPageExecutor(WrappedReportExecutor.java:49) ~[org.eclipse.birt.runtime_4.8.0-20180626-4.8.0.jar!/:na]	
at org.eclipse.birt.report.engine.internal.executor.dup.SuppressDuplciateReportExecutor.createPageExecutor(SuppressDuplciateReportExecutor.java:61) ~[org.eclipse.birt.runtime_4.8.0-20180626-4.8.0.jar!/:na]	
at org.eclipse.birt.report.engine.internal.executor.wrap.WrappedReportExecutor.createPageExecutor(WrappedReportExecutor.java:49) ~[org.eclipse.birt.runtime_4.8.0-20180626-4.8.0.jar!/:na]	
at org.eclipse.birt.report.engine.executor.ReportExecutorUtil.executeMasterPage(ReportExecutorUtil.java:63) ~[org.eclipse.birt.runtime_4.8.0-20180626-4.8.0.jar!/:na]	
at org.eclipse.birt.report.engine.layout.html.HTMLPageLM.start(HTMLPageLM.java:147) ~[org.eclipse.birt.runtime_4.8.0-20180626-4.8.0.jar!/:na]	at org.eclipse.birt.report.engine.layout.html.HTMLPageLM.layout(HTMLPageLM.java:91) ~[org.eclipse.birt.runtime_4.8.0-20180626-4.8.0.jar!/:na]	
at org.eclipse.birt.report.engine.layout.html.HTMLReportLayoutEngine.layout(HTMLReportLayoutEngine.java:100) ~[org.eclipse.birt.runtime_4.8.0-20180626-4.8.0.jar!/:na]	
at org.eclipse.birt.report.engine.presentation.ReportDocumentBuilder.build(ReportDocumentBuilder.java:249) ~[org.eclipse.birt.runtime_4.8.0-20180626-4.8.0.jar!/:na]	
at org.eclipse.birt.report.engine.api.impl.RunTask.doRun(RunTask.java:273) ~[org.eclipse.birt.runtime_4.8.0-20180626-4.8.0.jar!/:na]	at org.eclipse.birt.report.engine.api.impl.RunTask.run(RunTask.java:402) ~[org.eclipse.birt.runtime_4.8.0-20180626-4.8.0.jar!/:na]	
at com.innoventsolutions.birt.service.SubmitJobService.executeRun(SubmitJobService.java:200) ~[birt-engine-0.0.7.jar!/:0.0.7]	
at com.innoventsolutions.birt.service.SubmitJobService.lambda$executeRunThenRender$0(SubmitJobService.java:62) ~[birt-engine-0.0.7.jar!/:0.0.7]	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[na:na]	
at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) ~[na:na]	
at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[na:na]	
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[na:na]	
at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[na:na]	
at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[na:na]	
at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[na:na]
```

My connection string looks like this:

```
jdbc:sqlserver://XXXXX.database.windows.net;database=XXX;encrypt=true;trustServerCertificate=true;hostNameInCertificate=*.database.windows.net;loginTimeout=30;authentication=ActiveDirectoryServicePrincipal
```

**Comment by Bauer-David** [comment]
Full Logs:

[LOG_BIRT_DB_ERROR.txt](https://github.com/innoventsolutions/birt-spring-boot/files/13659747/LOG_BIRT_DB_ERROR.txt)
